[settings]
experimental = true

[tools]
sqlite = "3.46.0"
deno = "2.1.1"

[tasks."check:format"]
run = """
#!/usr/bin/env sh

set -ex

deno fmt --check --log-level trace
"""

[tasks."check:lint"]
run = """
#!/usr/bin/env sh

set -ex

deno lint
deno check --no-lock $(find . -type f | grep -E "\\.ts$|\\.tsx$" | grep -v "node_modules/")
"""
