#!/usr/bin/env sh

set -e

echo "=> Creating a $1 release."

final_tag=`npm version --git-tag-version=false $1`
./.bin/changelog-generator $final_tag > CHANGELOG.md

git add .
git commit --no-verify -sm "Release $final_tag" &>/dev/null

git tag $final_tag

echo "=> Release $final_tag created."
